name: Update Plugin Version on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Read plugin file from composer.json "name" field
        run: |
          NAME=$(jq -r '.name' composer.json)
          echo "Name from composer.json: $NAME"
          PLUGIN_NAME=${NAME#*/}
          PLUGIN_FILE="$PLUGIN_NAME.php"
          echo "Derived plugin file name: $PLUGIN_FILE"
          echo "PLUGIN_FILE=$PLUGIN_FILE" >> $GITHUB_ENV

      - name: Set plugin version in PHP file
        run: |
          TAG=${GITHUB_REF##*/}
          ESCAPED_TAG=$(printf '%s\n' "$TAG" | sed 's/[\/&]/\\&/g')

          echo "Before replacement:"
          head -n 10 "$PLUGIN_FILE"

          sed -i "s/^\(\s*\*\s*[Vv]ersion:\s*\).*/\1$ESCAPED_TAG/" "$PLUGIN_FILE"

          echo "After replacement:"
          head -n 10 "$PLUGIN_FILE"

      - name: Commit and push changes with reset + rebase + retry
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "=== GIT STATUS ==="
          git status
          
          echo "=== GIT DIFF (Plugin-Datei) ==="
          git diff "$PLUGIN_FILE" || echo "Keine Änderungen erkannt im Plugin-File!"
          
          git add "$PLUGIN_FILE"
          
          echo "=== GIT DIFF --staged (nach git add) ==="
          git diff --staged "$PLUGIN_FILE" || echo "Keine gestagten Änderungen!"
          
          echo "=== VERSUCH COMMIT ==="
          if git commit -m "chore: Update plugin version to $TAG [skip ci]"; then
          echo "Commit erfolgreich!"
          else
          echo "Kein Commit gemacht (vermutlich keine Änderungen)!"
          fi
          
          echo "=== PUSHEN ==="
          if git push origin HEAD:master; then
          echo "Push erfolgreich!"
          else
          echo "Push fehlgeschlagen!"
          git remote -v
          git branch -a
          fi

