name: Update Plugin Version on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Sync branch (fetch & reset)
        run: |
          git fetch origin master
          git reset --hard origin/master

      - name: Read plugin file path from composer.json
        run: |
          NAME=$(jq -r '.name' composer.json)
          PLUGIN_NAME=${NAME#*/}
          PLUGIN_FILE="$PLUGIN_NAME.php"
          echo "PLUGIN_FILE=$PLUGIN_FILE" >> $GITHUB_ENV
          echo "Plugin file path: $PLUGIN_FILE"

      - name: Update plugin version in PHP file
        run: |
          TAG=${GITHUB_REF##*/}
          ESCAPED_TAG=$(printf '%s\n' "$TAG" | sed 's/[\/&]/\\&/g')

          echo "Before replacement:"
          head -n 10 "$PLUGIN_FILE"

          sed -i "s/^\(\s*\*\s*[Vv]ersion:\s*\).*/\1$ESCAPED_TAG/" "$PLUGIN_FILE"

          echo "After replacement:"
          head -n 10 "$PLUGIN_FILE"

      - name: Commit and push changes with retry
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          RETRIES=5
          for i in $(seq 1 $RETRIES); do
            echo "Attempt $i to push..."

            git add "$PLUGIN_FILE"

            if git diff --cached --quiet; then
              echo "No changes to commit"
              break
            else
              git commit -m "chore: Update plugin version to $TAG [skip ci]"
            fi

            if git push origin master; then
              echo "Push successful!"
              break
            else
              echo "Push failed, retrying after 5 seconds..."
              sleep 5
              git fetch origin master
              git reset --hard origin/master
            fi
          done
