name: Update Plugin Version on Tag Push

on:
  push:
    tags:
      - '*'    # Jeder Tag löst die Action aus

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set plugin version in PHP file
        run: |
          TAG=${GITHUB_REF##*/}
          echo "Git Tag: '$TAG'"

          ESCAPED_TAG=$(printf '%s\n' "$TAG" | sed 's/[\/&]/\\&/g')
          echo "Escaped Tag: '$ESCAPED_TAG'"

          FILE="my-plugin.php"

          echo "Before replacement:"
          head -n 10 "$FILE"

          sed -i "s/^\(\s*\*\s*[Vv]ersion:\s*\).*/\1$ESCAPED_TAG/" "$FILE"

          echo "After replacement:"
          head -n 10 "$FILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add my-plugin.php

          git commit -m "chore: Update plugin version to $TAG [skip ci]" || echo "No changes to commit"

          git push origin HEAD:main
      
