name: Update Plugin Version on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Read plugin file from composer.json "name" field
        run: |
          NAME=$(jq -r '.name' composer.json)
          echo "Name from composer.json: $NAME"
          PLUGIN_NAME=${NAME#*/}
          PLUGIN_FILE="$PLUGIN_NAME.php"
          echo "Derived plugin file name: $PLUGIN_FILE"
          echo "PLUGIN_FILE=$PLUGIN_FILE" >> $GITHUB_ENV

      - name: Set plugin version in PHP file
        run: |
          TAG=${GITHUB_REF##*/}
          ESCAPED_TAG=$(printf '%s\n' "$TAG" | sed 's/[\/&]/\\&/g')

          echo "Before replacement:"
          head -n 10 "$PLUGIN_FILE"

          sed -i "s/^\(\s*\*\s*[Vv]ersion:\s*\).*/\1$ESCAPED_TAG/" "$PLUGIN_FILE"

          echo "After replacement:"
          head -n 10 "$PLUGIN_FILE"

      - name: Commit and push changes with rebase and retry
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          RETRIES=3
          for i in $(seq 1 $RETRIES); do
            echo "Attempt $i to fetch, rebase and push..."
            git fetch origin master
            if git rebase origin/master; then
              break
            else
              echo "Rebase failed, aborting and retrying..."
              git rebase --abort || true
              sleep 5
            fi
          done

          git add "$PLUGIN_FILE"
          git diff --quiet || git commit -m "chore: Update plugin version to $TAG [skip ci]"

          git push origin HEAD:master
