name: Update Plugin Version on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set plugin version in PHP file
        run: |
          TAG=${GITHUB_REF##*/}

          echo "Git Tag: '$TAG'"

          ESCAPED_TAG=$(printf '%s\n' "$TAG" | sed 's/[\/&]/\\&/g')
          echo "Escaped Tag: '$ESCAPED_TAG'"

          FILE="my-plugin.php"

          echo "Before replacement:"
          head -n 10 "$FILE"

          sed -i "s/^\(\s*\*\s*Version:\s*\).*/\1$ESCAPED_TAG/" "$FILE"

          echo "After replacement:"
          head -n 10 "$FILE"
      
